name: 'Install Python Requirements'
description: 'Install Python dependencies from requirements.txt with proper path handling'

inputs:
  requirements_path:
    description: 'Path to requirements.txt file (relative to working_directory)'
    required: false
    default: 'requirements.txt'
  working_directory:
    description: 'Working directory where requirements.txt is located'
    required: false
    default: '.'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
        cache-dependency-path: '${{ inputs.working_directory }}/${{ inputs.requirements_path }}'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r ${{ inputs.requirements_path }}
